# Generated by Django 5.1.2 on 2024-10-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'ethnie")),
                ('langue', models.CharField(max_length=255, verbose_name='Langue parlé')),
                ('description', models.TextField(verbose_name='Description')),
                ('histoire', models.TextField(verbose_name="Histoire de l'ethnie")),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_de_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Votre photo de profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'masculin'), ('Femme', 'Feminin')], max_length=10, verbose_name='Votre sexe'),
        ),
    ]
