# Generated by Django 5.1.2 on 2024-11-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_ethnies_alter_user_photo_de_profil_alter_user_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la langue')),
                ('ethnie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='langues', to='frontend.ethnies')),
            ],
        ),
    ]
