# Generated by Django 5.1.2 on 2024-11-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_langues'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
