# Generated by Django 5.1.2 on 2024-11-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(blank=True, max_length=32, verbose_name='Nom de famille'),
        ),
        migrations.AddField(
            model_name='user',
            name='prenoms',
            field=models.CharField(blank=True, max_length=64, verbose_name='Prénoms'),
        ),
    ]
