# Generated by Django 5.1.2 on 2024-11-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_user_nom_user_prenoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ethnies',
            name='langue',
        ),
    ]
