# Generated by Django 5.1.2 on 2024-11-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_remove_ethnies_langue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prenoms',
        ),
    ]
