# Generated by Django 5.1.2 on 2024-12-09 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_remove_user_nom_remove_user_prenoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ethnie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.ethnies'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Masculin'), ('Femme', 'Feminin')], max_length=10, verbose_name='SEXE'),
        ),
    ]
