# Generated by Django 5.1.2 on 2024-12-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_user_ethnie_alter_user_email_alter_user_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name="Titre de l'article")),
                ('description', models.TextField(verbose_name='Une petite description de votre podcast')),
                ('date_et_heure', models.DateTimeField(auto_now=True)),
                ('podcast_profil', models.ImageField(blank=True, null=True, upload_to='podcast_pictures/', verbose_name='Ajouter une photo')),
                ('appartenance', models.CharField(choices=[('apprendre', 'apprendre'), ('decouvrir', 'decouvrir')], max_length=12, verbose_name="sexion d'appartenance du podcast")),
            ],
        ),
    ]
