# Generated by Django 5.1.2 on 2025-01-14 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=55)),
                ('prix_entree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nbr_places_dispo', models.IntegerField()),
                ('media_profil_url', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='photo_evenement/')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=64)),
                ('auteur', models.CharField(max_length=64)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('media_url', models.ImageField(blank=True, default='photo_objetVente/default.jpg', null=True, upload_to='photo_objetVente/')),
            ],
        ),
        migrations.CreateModel(
            name='Thematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('deScription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('langue', models.CharField(choices=[('France', 'Français'), ('Angland', 'Anglais')], max_length=8)),
                ('date_et_heure', models.DateTimeField(auto_now=True)),
                ('photo_de_profil', models.ImageField(blank=True, null=True, upload_to='courses_pictures/', verbose_name='Une image de description pour le cours')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thematiques', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.thematique')),
            ],
        ),
        migrations.CreateModel(
            name='A_Apprendre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenue', models.TextField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=655)),
                ('contenu', models.TextField()),
                ('date_et_heure', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='file_reference/')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.cours')),
            ],
        ),
    ]
