# Generated by Django 5.1.2 on 2025-01-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_evenement_objetvente_thematique_cours_a_apprendre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='langue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.langues'),
        ),
    ]
