# Generated by Django 5.1.2 on 2025-01-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_cours_langue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thematique',
            old_name='deScription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='thematiques',
        ),
        migrations.AddField(
            model_name='cours',
            name='thematiques',
            field=models.ManyToManyField(blank=True, related_name='cours', to='frontend.thematique'),
        ),
    ]
