# Generated by Django 5.1.2 on 2025-01-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_rename_description_thematique_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='disponibilite',
            field=models.CharField(choices=[('ouvert', 'Ouvert pour inscription'), ('bientot', 'Bientôt'), ('en_cours', 'En cours'), ('archive', 'Archivé')], default='En cours', max_length=24, verbose_name='Disponibilité du cours'),
        ),
    ]
